### ISSUE TITLE
the graph is constructed in the mini-batch

### ISSUE THREAD

**Issue by jingzhengli** [KyleZheng1997/WCL#3]
Hi, thanks for the nice work. I have some concerns.
1) The graph is constructed in the mini-batch, if some images in mini-batch do not have neighbors with same labels, then the graph is useless.

> Please note that the weak label is generated from the 1-NN graph. To obtain the 1-NN graph, every node will be connected to the closest neighbor initially, so there is no such situation.
This manner forces each sample to connect the nearest neighbor; if some samples do not have the same category in the current mini-batch, thus such sample would connect to other sample with different categories.

**Comment by mingkai-zheng** [comment]
Please note that the weak label is generated from the 1-NN graph. To obtain the 1-NN graph, every node will be connected to the closest neighbor initially, so there is no such situation.

**Comment by jingzhengli** [comment]
> 

Thanks for your quick reply~ I have another question. The contrastive loss does not use memory-bank to collect history batches, whether the absence of a memory-bank has an impact on the experimental results. Thanks again

**Comment by mingkai-zheng** [comment]
We adopt a large batch size (4096) for the ImageNet experiments which should be sufficient for our algorithm. Although I haven't tried the memory bank trick, from my experience, an additional memory bank might only get marginal improvements.  You can find such a claim from the MoCoV3 paper [1].

[1]. An Empirical Study of Training Self-Supervised Visual Transformers.

**Comment by jingzhengli** [comment]
> 

Thanks, the large batch size is the reason for using "DistributedDataParallel".
