### ISSUE TITLE
The code for t-sne visualization

### ISSUE THREAD

**Issue by liuyuchen6666** [KyleZheng1997/WCL#5]
Hi,

Thanks for your great job!
Could you please provide the code for t-sne visualization？
Thanks very much.

**Comment by mingkai-zheng** [comment]
sorry, I could not find the visualization code since I have finished this project a long time ago. But I think this [tutorial](https://towardsdatascience.com/visualising-high-dimensional-datasets-using-pca-and-t-sne-in-python-8ef87e7915b) is a good start for you

**Comment by liuyuchen6666** [comment]
So the t-sne is conducted on 2048-dimensional feature or 128-dimension feature space?
On 4/5/2022 ***@***.***> wrote：

sorry, I could not find the visualization code since I have finished this project a long time ago. But I think this tutorial is a good start for you

**Comment by mingkai-zheng** [comment]
I provided the 2048-D visualization results in my paper, however, I also tried the 128-D feature which actually produces quite similar results.

**Comment by liuyuchen6666** [comment]
Thanks a lot for your help!

|
|
|
|
|
On 4/5/2022 ***@***.***> wrote：

I provided the 2048-D visualization results in my paper, however, I also tried the 128-D feature which actually produces quite similar results.
